### ISSUE TITLE
Is it possible to compile and run on aarch64?

### ISSUE THREAD

**Issue by dokoma** [JohnnyonFlame/droidports#10]
I compiled it but it runs into "out of memory" error. would you like to tell me if I got the wrong direction?

**Comment by JohnnyonFlame** [comment]
The rewrite I'm doing to support newer GameMaker Studio versions also supports aarch64, stay tuned.

**Comment by JohnnyonFlame** [comment]
@dokoma Might want to head over to [GMLoader-next](https://github.com/johnnyonFlame/gmloader-next). Keep in mind only gms 2 and up have aarch64.

**Comment by dokoma** [comment]
Thanks for your concern! I have cloned that 2 days ago, and it looks hard for me to build, Long story to short : my cross compiler toolchain has only gcc7 ,  so  I stuck at  thunks/libc/misc.cpp  .  My initial intention is  to make am2r runs on my aarch64-only handheld,( as far as I know, the am2r is gms14 only? ), and you remind me only gms2 support aarch64, so...  is my wish possible?

**Comment by JohnnyonFlame** [comment]
Open an issue on GMLoader-next providing your build logs and other information you might have.
